CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_name CHAR VARYING(255) NOT NULL,
    user_firstname CHAR VARYING(255) NOT NULL,
    user_lastname CHAR VARYING(255) NOT NULL,
    user_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_active BOOLEAN DEFAULT TRUE
)