apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: task-pv-pod
        image: mysql:latest
        ports:
        - containerPort: 3311
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"

      - name: user-pv-pod
        image: mysql:latest
        ports:
        - containerPort: 3312
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
