CREATE TABLE IF NOT EXISTS tasks (
    task_id INTEGER PRIMARY KEY AUTOINCREMENT,
    task_title CHAR VARYING(255) NOT NULL,
    task_description CHAR VARYING(2000) NOT NULL,
    task_status ENUM('PENDING', 'COMPLETED') DEFAULT 'PENDING',
    task_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    task_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    task_active BOOLEAN DEFAULT TRUE
)